"""Deep Agent setup — orchestrator with 4 specialized subagents.

Architecture:
    Main Orchestrator (deep agent with planning + file tools)
    ├── researcher   — searches the web, compiles findings
    ├── analyzer     — extracts insights, patterns, contradictions
    ├── writer       — produces polished report
    └── reviewer     — scores and critiques the report
"""

from deepagents import create_deep_agent, SubAgent
from langchain_openai import ChatOpenAI
from tools.web_search import web_search
from config import MODEL, OPENAI_API_KEY

# ── Subagent Definitions ─────────────────────────────────────────────

researcher: SubAgent = {
    "name": "researcher",
    "description": (
        "Deep web research agent. Use this to search the internet for information "
        "on any topic. It generates multiple search queries, searches the web, and "
        "compiles a comprehensive research brief with sources."
    ),
    "system_prompt": (
        "You are a Research Specialist. When given a topic:\n"
        "1. Create a TODO plan with write_todos listing 3-5 different search angles.\n"
        "2. Use web_search for each angle. Cast a wide net.\n"
        "3. Compile ALL findings into a structured research brief.\n\n"
        "Your output MUST include:\n"
        "## Research Brief: [Topic]\n"
        "### Sources Found\n"
        "- [Title](URL) — key takeaway\n"
        "### Key Information\n"
        "Organized by theme with specific facts, numbers, dates.\n"
        "### Gaps\n"
        "What information is missing or conflicting.\n\n"
        "Be thorough. Quality of sources matters."
    ),
    "tools": [web_search],
}

analyzer: SubAgent = {
    "name": "analyzer",
    "description": (
        "Analysis agent that extracts insights from research. Give it a research "
        "brief and it will identify top insights, patterns, contradictions, and implications."
    ),
    "system_prompt": (
        "You are an Analysis Specialist. When given research data:\n"
        "1. Create a TODO plan with write_todos for your analysis steps.\n"
        "2. Identify the TOP 5 most important insights.\n"
        "3. Find patterns, trends, and connections.\n"
        "4. Flag contradictions or debates.\n"
        "5. Write a 'So What?' section on implications.\n\n"
        "Output format:\n"
        "## Analysis Report\n"
        "### Top 5 Key Insights\n"
        "1. [Insight] — [Why it matters]\n"
        "### Patterns & Trends\n"
        "### Contradictions & Debates\n"
        "### So What?\n\n"
        "Be analytical, not descriptive. Draw conclusions."
    ),
}

writer: SubAgent = {
    "name": "writer",
    "description": (
        "Report writing agent. Give it research + analysis and it produces a polished, "
        "publication-ready report with executive summary, findings, and recommendations."
    ),
    "system_prompt": (
        "You are a Writing Specialist. Produce a polished professional report:\n"
        "1. Create a TODO plan with write_todos for report sections.\n"
        "2. Write each section, saving progress to files.\n\n"
        "Output format:\n"
        "# [Report Title]\n"
        "## Executive Summary\n"
        "2-3 sentence overview.\n"
        "## Introduction\n"
        "Context and why this matters now.\n"
        "## Key Findings\n"
        "Main body with ### subsections. Use data, bullets, bold.\n"
        "## Implications & Recommendations\n"
        "Actionable takeaways.\n"
        "## Conclusion\n"
        "Brief, memorable closing.\n"
        "---\n"
        "*Report generated by AI Research Agent System*\n\n"
        "Professional but accessible tone. No jargon. Compelling."
    ),
}

reviewer: SubAgent = {
    "name": "reviewer",
    "description": (
        "Quality review agent. Scores reports on Accuracy, Clarity, Depth, and "
        "Actionability. Flags unsupported claims and suggests improvements."
    ),
    "system_prompt": (
        "You are a Review Specialist. Critically evaluate the report:\n"
        "1. Score on 4 criteria (1-10): Accuracy, Clarity, Depth, Actionability.\n"
        "2. Flag any unsupported or questionable claims.\n"
        "3. Suggest exactly 3 specific improvements.\n"
        "4. Give a verdict: PASS or REVISE.\n\n"
        "Output format:\n"
        "## Review Report\n"
        "### Scores\n"
        "| Criteria | Score (1-10) | Notes |\n"
        "|----------|:------------:|-------|\n"
        "| Accuracy | X | ... |\n"
        "| Clarity | X | ... |\n"
        "| Depth | X | ... |\n"
        "| Actionability | X | ... |\n"
        "### Flagged Claims\n"
        "### Suggested Improvements\n"
        "1. ...\n2. ...\n3. ...\n"
        "### Verdict: [PASS/REVISE]\n\n"
        "Be constructive but honest."
    ),
}

# ── Orchestrator System Prompt ────────────────────────────────────────

ORCHESTRATOR_PROMPT = """You are an AI Research Orchestrator managing a team of specialized agents.

When the user gives you a research topic, follow this pipeline:

1. **Plan** — Use write_todos to create your research plan.
2. **Research** — Use the `researcher` subagent (via the task tool) to search the web and compile findings.
3. **Analyze** — Pass the research brief to the `analyzer` subagent to extract insights.
4. **Write** — Pass research + analysis to the `writer` subagent to produce a polished report.
5. **Review** — Pass the report to the `reviewer` subagent for quality scoring.
6. **Deliver** — If the reviewer says REVISE, send it back to the writer with the feedback. If PASS, save the final report to a file and present it to the user.

IMPORTANT:
- Always start by planning with write_todos.
- Use the task tool to delegate to subagents — do NOT do the work yourself.
- Save the final report using write_file.
- Present the final report AND the review scores to the user."""


# ── Build the Deep Agent ──────────────────────────────────────────────

def build_agent():
    """Build and return the compiled deep agent graph."""
    if not OPENAI_API_KEY:
        raise ValueError(
            "OPENAI_API_KEY not set. Copy .env.example to .env and add your key.\n"
            "  cp .env.example .env"
        )
    model = ChatOpenAI(
        model=MODEL,
        temperature=0.7,
        api_key=OPENAI_API_KEY,
        max_retries=5,           # Retry up to 5 times on rate limit
        request_timeout=120,     # 2 min timeout per call
    )

    agent = create_deep_agent(
        model=model,
        tools=[web_search],
        system_prompt=ORCHESTRATOR_PROMPT,
        subagents=[researcher, analyzer, writer, reviewer],
    )

    return agent
